<?php
require("negocio.acesso.php");
require("negocio.associacao.php");
require("negocio.associacaoFoto.php");
require("negocio.atleta.php");
require("negocio.cidade.php");
require("negocio.diretoria.php");
require("negocio.email.php");
require("negocio.galeria.php");
require("negocio.galeriaImagem.php");
require("negocio.log.php");
require("negocio.menu.php");
require("negocio.noticia.php");
require("negocio.pagina.php");
require("negocio.perfil.php");
require("negocio.permissao.php");
require("negocio.pessoa.php");
require("negocio.post.php");
require("negocio.usuario.php");
require("negocio.uf.php");
require("negocio.fileBrowser.php");
require("dominio.categoria.php");
?>