<?php
require("negocio.acesso.php");
require("negocio.ano.php");
require("negocio.anuidade.php");
require("negocio.associacao.php");
require("negocio.associacaoFoto.php");
require("negocio.atleta.php");
require("negocio.categoria.php");
require("negocio.cidade.php");
require("negocio.classe.php");
require("negocio.competicao.php");
require("negocio.configuracoes.php");
require("negocio.custa.php");
require("negocio.diretoria.php");
require("negocio.email.php");
require("negocio.galeria.php");
require("negocio.galeriaImagem.php");
require("negocio.graduacao.php");
require("negocio.grupoCompeticao.php");
require("negocio.historicoGraduacao.php");
require("negocio.inscricao.php");
require("negocio.log.php");
require("negocio.menu.php");
require("negocio.noticia.php");
require("negocio.pagamento.php");
require("negocio.pagamentoItem.php");
require("negocio.pagamentoTipo.php");
require("negocio.pagina.php");
require("negocio.perfil.php");
require("negocio.permissao.php");
require("negocio.pessoa.php");
require("negocio.post.php");
require("negocio.tipoPagamento.php");
require("negocio.usuario.php");
require("negocio.uf.php");
require("dominio.tipoCampeonato.php");
require("dominio.categoria.php");
require("dominio.grupoCusta.php");


?>