INSERT INTO `fmj_menu` (`id`, `idMenuPai`, `nome`, `ordem`, `url`, `icone`) VALUES (NULL, NULL, 'Cadastros', '1', '', 'fa-table');
UPDATE `fmj_menu` SET `idMenuPai` = '27' WHERE `fmj_menu`.`id` = 25;
INSERT INTO `fmj_menu` (`id`, `idMenuPai`, `nome`, `ordem`, `url`, `icone`) VALUES (NULL, '27', 'Atletas', '2', 'admin_atleta', 'fa-child');
ALTER TABLE `fmj_atleta` DROP FOREIGN KEY `fk_fmj_atleta_fmj_cidade1`;
ALTER TABLE `fmj_atleta` DROP `naturalidade`;
ALTER TABLE `fmj_atleta` DROP `nacionalidade`;
ALTER TABLE `fmj_pessoa` ADD `nacionalidade` VARCHAR(100) NOT NULL ;
ALTER TABLE `fmj_pessoa` DROP `cidade`;
ALTER TABLE `fmj_pessoa` DROP `estado`;
ALTER TABLE `fmj_pessoa` DROP `anuidade`;
ALTER TABLE `fmj_pessoa` DROP `contador`;
ALTER TABLE `fmj_pessoa` ADD `idCidadeNaturalidade` BIGINT NULL , ADD INDEX (`idCidadeNaturalidade`) ;
ALTER TABLE `fmj_pessoa` ADD CONSTRAINT `fk_fmj_pessoa_fmj_cidade2` FOREIGN KEY (`idCidadeNaturalidade`) REFERENCES `fmj_cidade`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE `fmj_pessoa` DROP `bitAtivo`, DROP `academia`;
ALTER TABLE `fmj_pessoa` CHANGE `nacionalidade` `nacionalidade` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE `fmj_atleta` DROP `filiacaoPai`, DROP `filiacaoMae`;
ALTER TABLE `fmj_atleta` DROP FOREIGN KEY `fk_fmj_atleta_fmj_estado_civil1`;
ALTER TABLE `fmj_atleta` DROP `idEstadoCivil`;
ALTER TABLE `fmj_atleta` DROP `profissao`, DROP `enderecoComercial`, DROP `telComercial`;
ALTER TABLE `fmj_pessoa` ADD `sexo` VARCHAR(1) NULL ;
ALTER TABLE `fmj_atleta` ADD `bitAtivo` TINYINT(4) NOT NULL DEFAULT '1' ;
ALTER TABLE `fmj_associacao` CHANGE `bitAtivo` `bitAtivo` TINYINT(4) NULL DEFAULT '1';
ALTER TABLE `fmj_usuario` CHANGE `ativo` `ativo` TINYINT(1) NOT NULL DEFAULT '1';